---
- name: Cleanup unused GCP images
  hosts: localhost
  connection: local
  vars:
    gcp_project_id: ""
    gcp_service_account_file: ""
    instruqt_api_token: 
  tasks:


    - name: Execute GraphQL query for track images
      ansible.builtin.uri:
        url: https://play.instruqt.com/graphql
        method: POST
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ instruqt_api_token }}"
        body: |
          {
            "query": "query trackimages { tracks(organizationSlug: \"redhat\", orderBy: title_ASC) { slug title maintenance config { virtualmachines { image machine_type } } } }"
          }
        body_format: json
      register: graphql_response
      failed_when: graphql_response.status != 200
      check_mode: false

    - name: Extract VM images from GraphQL response
      ansible.builtin.set_fact:
        vm_images: "{{ graphql_response.json.data.tracks | json_query('[].config.virtualmachines[].image') | unique }}"

    - name: Filter VM images to include only project ID
      ansible.builtin.set_fact:
        instruqt_images: "{{ vm_images | select('search', '^{{ gcp_project_id }}/') | list }}"

    - name: Display the filtered VM images
      ansible.builtin.debug:
        var: instruqt_images

    - name: Get list of all VM images in the project
      google.cloud.gcp_compute_image_info:
        auth_kind: serviceaccount
        service_account_file: "{{ gcp_service_account_file }}"
        project: "{{ gcp_project_id }}"
      register: gcp_images
      failed_when: gcp_images.resources is not defined or gcp_images.resources | length == 0
      check_mode: false

    - name: Filter packer-created images
      ansible.builtin.set_fact:
        packer_images: >-
          {{ gcp_images.resources
             | selectattr('description', 'defined')
             | selectattr('description', 'search', 'Created by Packer')
             | map(attribute='name')
             | list }}

    - name: Display packer-created images
      ansible.builtin.debug:
        msg: "{{ packer_images }}"

    - name: Normalize Instruqt image names (remove prefix)
      ansible.builtin.set_fact:
        instruqt_images_normalized: "{{ instruqt_images | map('regex_replace', '^{{ gcp_project_id }}/', '') | list }}"

    - name: Determine images to delete
      ansible.builtin.set_fact:
        deletable_images: "{{ packer_images | difference(instruqt_images_normalized) }}"

    - name: Display images that can be deleted
      ansible.builtin.debug:
        var: deletable_images

    - name: Check-mode simulation of deletions
      ansible.builtin.debug:
        msg: "Image {{ item }} would be deleted"
      loop: "{{ deletable_images }}"
      when: ansible_check_mode

    - name: Delete unused images
      google.cloud.gcp_compute_image:
        auth_kind: serviceaccount
        service_account_file: "{{ gcp_service_account_file }}"
        project: "{{ gcp_project_id }}"
        name: "{{ item }}"
        state: absent
      loop: "{{ deletable_images }}"
      when: deletable_images | length > 0
      register: delete_results
